/**
 * GraphQL query sanitization
 * Validates queries generated by Gemini before executing against Monday.com
 */

const ALLOWED_OPERATIONS = ['query', 'mutation'];
const MAX_QUERY_LENGTH = 2000;

const BLOCKED_PATTERNS = [
  /__schema/i,
  /__type/i,
  /introspection/i,
];

function sanitizeQuery(query, allowedBoardId) {
  if (!query || typeof query !== 'string') {
    return { valid: false, error: 'Query must be a non-empty string' };
  }

  const trimmed = query.trim();

  if (trimmed.length > MAX_QUERY_LENGTH) {
    return { valid: false, error: `Query exceeds maximum length of ${MAX_QUERY_LENGTH}` };
  }

  const startsWithAllowed = ALLOWED_OPERATIONS.some(op =>
    trimmed.toLowerCase().startsWith(op)
  );
  if (!startsWithAllowed) {
    return { valid: false, error: 'Query must start with "query" or "mutation"' };
  }

  for (const pattern of BLOCKED_PATTERNS) {
    if (pattern.test(trimmed)) {
      return { valid: false, error: `Query contains blocked pattern: ${pattern}` };
    }
  }

  // Ensure queries only target the configured board
  if (allowedBoardId) {
    const boardIdRefs = trimmed.match(/board_id:\s*(\d+)/g) || [];
    for (const ref of boardIdRefs) {
      const id = ref.replace(/board_id:\s*/, '');
      if (id !== allowedBoardId) {
        return { valid: false, error: `Query targets unauthorized board: ${id}` };
      }
    }

    const boardsRefs = trimmed.match(/boards\(ids:\s*\[(\d+)\]/g) || [];
    for (const ref of boardsRefs) {
      const id = ref.match(/\[(\d+)\]/)?.[1];
      if (id && id !== allowedBoardId) {
        return { valid: false, error: `Query targets unauthorized board: ${id}` };
      }
    }
  }

  return { valid: true, sanitized: trimmed };
}

function sanitizeQueries(queries, allowedBoardId) {
  if (!Array.isArray(queries)) {
    return { valid: false, errors: ['Queries must be an array'], sanitized: [] };
  }

  const sanitized = [];
  const errors = [];

  for (let i = 0; i < queries.length; i++) {
    const result = sanitizeQuery(queries[i], allowedBoardId);
    if (result.valid) {
      sanitized.push(result.sanitized);
    } else {
      errors.push(`Query ${i + 1}: ${result.error}`);
    }
  }

  if (errors.length > 0) {
    return { valid: false, errors, sanitized };
  }

  return { valid: true, errors: [], sanitized };
}

module.exports = { sanitizeQuery, sanitizeQueries };
